version: '2.1'

services:
  app:
    image: "federicorossir/coap-browser:latest"
    ports:
        - "8080:8080"
    networks:
      app_net:
        ipv6_address: "AAAA:9400:1000:7::DEAD"
networks:
  app_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "AAAA:9400:1000:7::/64"
